### ISSUE TITLE
Chromosome names

### ISSUE THREAD

**Issue by Liverworks** [maiziex/Aquila_stLFR#5]
Hi!

I am trying to use Aquila_stLFR for an animal species. My reference fasta has chromosome names like Scaffold_[number], not chr[number].

Preprocessing was OK, but on step1 I get errors:

```
4799941
36.012870783203375
21.0
389026.0
3.0
Traceback (most recent call last):
  File "/home/aglushkevich/.conda/envs/anpython3/lib/python3.7/site-packages/bin/Run_h5_all_multithreads.py", line 148, in save_variant_dict
    chr_num = int(data[0][3:])
ValueError: invalid literal for int() with base 10: 'ffold_2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aglushkevich/.conda/envs/anpython3/lib/python3.7/site-packages/bin/Run_h5_all_multithreads.py", line 591, in <module>
    variant_dict = save_variant_dict(vcf_file,mbq_threshold,avg_depth,out_dir)
  File "/home/aglushkevich/.conda/envs/anpython3/lib/python3.7/site-packages/bin/Run_h5_all_multithreads.py", line 190, in save_variant_dict
    variant_dict[(chr_num,pos)] = [ref,alt,GT]
UnboundLocalError: local variable 'chr_num' referenced before assignment
[main_samview] region "chr16" specifies an unknown reference name. Continue anyway.
[main_samview] region "chr1" specifies an unknown reference name. Continue anyway.
[main_samview] region "chr2" specifies an unknown reference name. Continue anyway.
samtools depth: can't parse region "chr16"
samtools depth: can't parse region "chr2"
samtools depth: can't parse region "chr1"

```

Can it be fixed, or should I change my reference contig names?

**Comment by maiziex** [comment]
Hi, Aquila_stLFR only uses regular reference fasta file and the contig name needs to be "chr1", "chr2", etc.

**Comment by maiziex** [comment]
Hi, Aquila_stLFR only uses regular reference fasta file and the contig name needs to be "chr1", "chr2", etc.


Maizie (Xin) Zhou, Ph.D.
Assistant Professor
Biomedical Engineering, Computer Science, and Data Science Institute
Vanderbilt University

5919 Stevenson Center

Nashville, TN  37235

Phone:  615-343-6843

https://lab.vanderbilt.edu/maizie-zhou-lab/<https://lab.vanderbilt.edu/maizie-zhou-lab/>
<https://lab.vanderbilt.edu/maizie-zhou-lab/>
________________________________
From: Liverworks ***@***.***>
Sent: Friday, October 7, 2022 3:53 AM
To: maiziex/Aquila_stLFR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [maiziex/Aquila_stLFR] Chromosome names (Issue #5)


Hi!

I am trying to use Aquila_stLFR for an animal species. My reference fasta has chromosome names like Scaffold_[number], not chr[number].

Preprocessing was OK, but on step1 I get errors:

`4799941
36.012870783203375
21.0
389026.0
3.0
Traceback (most recent call last):
File "/home/aglushkevich/.conda/envs/anpython3/lib/python3.7/site-packages/bin/Run_h5_all_multithreads.py", line 148, in save_variant_dict
chr_num = int(data[0][3:])
ValueError: invalid literal for int() with base 10: 'ffold_2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/aglushkevich/.conda/envs/anpython3/lib/python3.7/site-packages/bin/Run_h5_all_multithreads.py", line 591, in
variant_dict = save_variant_dict(vcf_file,mbq_threshold,avg_depth,out_dir)
File "/home/aglushkevich/.conda/envs/anpython3/lib/python3.7/site-packages/bin/Run_h5_all_multithreads.py", line 190, in save_variant_dict
variant_dict[(chr_num,pos)] = [ref,alt,GT]
UnboundLocalError: local variable 'chr_num' referenced before assignment
[main_samview] region "chr16" specifies an unknown reference name. Continue anyway.
[main_samview] region "chr1" specifies an unknown reference name. Continue anyway.
[main_samview] region "chr2" specifies an unknown reference name. Continue anyway.
samtools depth: can't parse region "chr16"
samtools depth: can't parse region "chr2"
samtools depth: can't parse region "chr1"
`

Can it be fixed, or should I change my reference contig names?
